
# Site information
title: "FOSS Academic"
title_separator: "|"
name: "Robert W. Gehl"
description: "A blog dedicated to two things. First, an exploration of Free and Open Source tools useful to academics. Second, an exploration of the culture, politics, and practices of FOSS."
url: "https://fossacademic.tech"

# These are collections of files. Authors, for example, is a collection of author profile files.
collections:
  authors:
    output: true
  tags:
    output: true

# this sets the layouts for each type of page -- authors, posts, default
defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
    values:
      layout: "tags"

#plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-archives

#excerpt separator
excerpt_separator: <!-- more -->



